spring:
  groovy:
    template:
      check-template-location: false
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
logging:
  config: classpath:logback.groovy
canal:
  client:
    instances:
      example:
        host: 127.0.0.1
        port: 11111
        batch-size: 1000
        cluster-enabled: false
        zookeeper-address:
sync:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    schema: http
  config:
    mapping:
      - enabled: true
        table-name: pt_petition_case
        fields:
          - field-name: id
            mapping-name: id
            show: true
          - field-name: no
            mapping-name: bianhao
            show: true